# Windows is currently not supported.
# name: Windows CI

# on:
  # schedule:
    # - cron: "0 6 * * *"
  # push:
  # pull_request:

# jobs:
#   ci-tests:
#     runs-on: windows-latest
#     strategy:
#       matrix:
#         python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
#     name: Windows CI
#     steps:
#       - name: Check out source repository
#         uses: actions/checkout@v2
#       - name: Set up Python ${{ matrix.python-version }} environment
#         uses: actions/setup-python@v1
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Python environment report
#         run: python -c "import sys; print(sys.version)"
#       - name: Run ${{ matrix.python-version }} platform tests (default)
#         uses: reviewdog/action-flake8@master
#         with:
#           path: "tests/test-default.py" # have to restrict because there are other tests with flake8 fails
#       - name: Run ${{ matrix.python-version }} platform tests (with args)
#         uses: reviewdog/action-flake8@master
#         with:
#           update_pip: "true"
#           ignore: "F401"
#           exclude: "tests/test.py"
#           max_line_length: "100"
#           args: "--quiet"
#           path: "tests/test-args.py"
#           flake8_version: "master"